# Generated by Django 3.1.6 on 2021-02-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychotherapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaded', models.DateField(auto_now=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
